### PR TITLE
Update handling removal of python path

### PR DESCRIPTION
**Pull request by shadowwalkersb**
@aali1987 , can you check if this change works?

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
This is not urgent, if testing is not trivial.

**Comment by aali1987** [comment]
@shadowwalkersb     I will try to install this pydusa version and if installation goes fine I will try to run our test just to check whether everything is fine or not..... once it is done I will let you know. ( either today or on Monday) .

**Comment by shadowwalkersb** [comment]
I can upload a dev version of eman-deps with the change here, if it's going to help.

**Comment by aali1987** [comment]
That would be perfect so that i can directly install it by just changing the eman-deps version in the eman installation .

**Comment by aali1987** [comment]
Because i tried to compile it by downloading the git ..........   ./configure works fine but when I do    make then it gives me an error ```checking for python... /home/adnan/applications/sphire/miniconda3/envs/pydusa_test/bin/python
checking for python include directory...   File "<string>", line 1
    import sys; print sys.version[:3]
                        ^
SyntaxError: invalid syntax
  File "<string>", line 1
    import sys; print sys.prefix
                        ^
SyntaxError: invalid syntax
configure: error: Unable to find Python.h!
Makefile:210: recipe for target 'config.status' failed
make: *** [config.status] Error 1
```

**Comment by shadowwalkersb** [comment]
Can you try installing pydusa 1.30? `eman-deps` won't like it, so you can force-install.

`conda install pydusa=1.30 -c cryoem -c defaults -c conda-forge`

If that doesn't work, I will try to upload `eman-deps` with that pydusa.

**Comment by shadowwalkersb** [comment]
Installing pydusa 1.3 is taking some time and it may not install at all. So, let me work on eman-deps and I will let you know. It may take some time, though. Thanks for helping with testing!

**Comment by aali1987** [comment]
Yeah my installation of pydusa is still running .  But it is giving conflicts .
(pydusa_test) adnan@ ~/PycharmProjects/pydusa (master) $conda install pydusa=1.30 -c cryoem -c defaults -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for python-dateutil grpcio pyqt keras-preprocessing rsa pycparser pexpect google-auth-oauthlib mkl_random kiwisolver nump\ ^Examining conflict for python-dateutil grpcio pyqt keras-preprocessing rsa pycparser pexpect google-auth-oauthlib mkl_random kiwisolver numpy

**Comment by shadowwalkersb** [comment]
OK, I will prepare a new version of `eman-deps`.

**Comment by aali1987** [comment]
Yeah let me know whenever you are done with creating the new eman-deps version . For testing the new changes ....I can do them on the weekend also.

**Comment by aali1987** [comment]
Just another query related to eman-deps installation ..... Right now it takes around 30 mins to 1 hour for installing eman-deps . Is there any way in the future the installation time can speed up a little .

**Comment by shadowwalkersb** [comment]
Set your conda to have flexible channel priority. It still takes longer than I like, but it shouldn't take more than 5 minutes.

https://blake.bcm.edu/emanwiki/EMAN2/COMPILE_EMAN2_ANACONDA/2.39#CA-d423562a6129dd0763e3cde3e7407f8fc2dcc6d4_6

``` sh
# Flexible channel priority works better for eman-deps
  conda config --set channel_priority flexible
```

After the release, we will be updating the dependencies which may help with conflicts and install time.

**Comment by shadowwalkersb** [comment]
> Yeah let me know whenever you are done with creating the new eman-deps version . For testing the new changes

`conda install eman-deps=25.0 -c cryoem/label/dev -c cryoem -c defaults -c conda-forge`

**Comment by aali1987** [comment]
Hi @shadowwalkersb  . I installed the eman-deps=25.0 which you recommended .... but unfortunately our test failed when running the mpi-used programs. It gives a segmentation fault which is linked to mpi.so. If i run the same program with the standards eman-deps version then I dont get any  segmentation fault.

**Comment by aali1987** [comment]
[error_log_meridien.txt](https://github.com/cryoem/pydusa/files/5841923/error_log_meridien.txt)

**Comment by aali1987** [comment]
I have attached a log file (error_log_meridien.txt) where you can see the error it generates.

**Comment by aali1987** [comment]
I have also attached conda_info_pydusa.txt and  conda_list_pydusa.txt   for envrionment information.

**Comment by aali1987** [comment]
[conda_info_pydusa.txt](https://github.com/cryoem/pydusa/files/5842473/conda_info_pydusa.txt)
[conda_list_pydusa.txt](https://github.com/cryoem/pydusa/files/5842475/conda_list_pydusa.txt)

**Comment by shadowwalkersb** [comment]
The change here is replacing the hard-coded python version with macros, so every time we update python, we don't have to change pydusa code. Can you come up with a simple script that calls `mpi_iterefa` which is where the change is here? I will try to debug.

**Comment by aali1987** [comment]
@shadowwalkersb   here is a simple script that you can use to test the mpi_iterefa function call. 
The only thing you need to change in the python code volume name .  The rest should be fine . 
I ran the code with two different conda environment . one with standard pydusa and the other with eman-deps=25.0.

The code ran without a problem in case of standard pydusa.  But when I ran the code with pydusa from eman-deps=25.0 then it gave the same segmentation fault as before.
Hope it helps :)

[pydusa_mpi_testing.txt](https://github.com/cryoem/pydusa/files/5850412/pydusa_mpi_testing.txt)

**Comment by shadowwalkersb** [comment]
This should be good now. Can you give it another try? The script was helpful.

**Comment by aali1987** [comment]
I tried to create a fresh installation with eman-deps=25.0 but it gave me an error when doing cmake.  

(pydusa_test_v1) adnan@ $cmake /home/adnan/PycharmProjects/EmanforPydusa/ -DENABLE_OPTIMIZE_MACHINE=ON

CMake Error at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.14 or higher is required.  You are running version 3.10.2

It did not gave me this error before.

Do I need to use a different eman-deps version for testing ??

**Comment by shadowwalkersb** [comment]
Use eman-deps-dev.

`conda install eman-deps-dev=25.0 -c cryoem/label/dev -c cryoem -c defaults -c conda-forge`

**Comment by aali1987** [comment]
If i install the environment the way you mentioned then the problem is that even though the conda installation works fine but when I tried to make -j then it gives me an error  " make: *** No targets specified and no makefile found.  Stop. "

**Comment by aali1987** [comment]
Here is the log when I do cmake . 
```(pydusa_test_v1) adnan@ ~/PycharmProjects/EmanforPydusa/pyd_build (master) $cmake /home/adnan/PycharmProjects/EmanforPydusa/ -DENABLE_OPTIMIZE_MACHINE=ON
-- CMAKE_PREFIX_PATH="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1;/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/.."
PYTHON_EXECUTABLE:   /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/bin/python
PYTHON_LIBRARIES:    /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libpython3.7m.so
PYTHON_INCLUDE_DIRS: /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/include/python3.7m
PYTHON_INCLUDE_PATH: /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/include/python3.7m
PYTHON_INCLUDE_DIR:  /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/include/python3.7m
Python site-packages: /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/python3.7/site-packages
-- PYTHON_LIB_SHARED="0"
-- CMAKE_CXX_COMPILER_ID="GNU"
-- NUMPY_INCLUDE_DIR="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/python3.7/site-packages/numpy/core/include"
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   python37
--   numpy37
Boost_LIBRARIES:   /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libboost_python37.so;/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libboost_numpy37.so
Boost_INCLUDE_DIR: /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/include
-- HDF5_LIBRARY="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libhdf5.so"
-- TIFF_LIBRARIES="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libtiff.so"
-- JPEG_LIBRARIES="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libjpeg.so"
-- PNG_LIBRARIES="/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libpng.so;/home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libz.so"
-- OPENGL_INCLUDE_DIR="/usr/include"
-- OPENGL_LIBRARIES="/usr/lib/x86_64-linux-gnu/libOpenGL.so;/usr/lib/x86_64-linux-gnu/libGLX.so;/usr/lib/x86_64-linux-gnu/libGLU.so"
-- OPENGL_glu_LIBRARY="/usr/lib/x86_64-linux-gnu/libGLU.so"
-- OPENGL_opengl_LIBRARY="/usr/lib/x86_64-linux-gnu/libOpenGL.so"
-- OPENGL_gl_LIBRARY=""
-- OPENGL_FOUND="TRUE"
-- OPENGL_GLU_FOUND="YES"
-- OpenGL_OpenGL_FOUND="TRUE"
-- OPENGL_opengl_LIBRARY="/usr/lib/x86_64-linux-gnu/libOpenGL.so"
-- OPENGL_gl_LIBRARY=""
Target OpenGL exists.
Target OpenGL::OpenGL exists.
Target OpenGL::GL exists.
Target OpenGL::GLU exists.
FREETYPE_LIBRARIES:    /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/lib/libfreetype.so
FREETYPE_INCLUDE_DIRS: /home/adnan/applications/sphire/miniconda3/envs/pydusa_test_v1/include/freetype2
-- EMAN_GITDIR="/home/adnan/PycharmProjects/EmanforPydusa"
-- CMAKE_SOURCE_DIR="/home/adnan/PycharmProjects/EmanforPydusa"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adnan/PycharmProjects/EmanforPydusa
(pydusa_test_v1) adnan@ ~/PycharmProjects/EmanforPydusa/pyd_build (master) $make -j
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by aali1987** [comment]
Also after the execution of cmake command ....... the build folder is still empty which is very strange 
I used the following command for cmake ```cmake /home/adnan/PycharmProjects/EmanforPydusa/ -DENABLE_OPTIMIZE_MACHINE=ON```

**Comment by shadowwalkersb** [comment]
> -- Build files have been written to: /home/adnan/PycharmProjects/EmanforPydusa

Your source and build directories seem to be mixed up?

**Comment by aali1987** [comment]
yeah sorry that was my mistake ...dont know what went wrong but i just created a fresh repo and make new build files. All went fine then.  I ran the mpi used code and I did not receive any error or segmentation faults till now . So i guess the solution worked.

**Pull request merged**
