### PR TITLE
Add fftw things

### PR DESCRIPTION
**Pull request by mstabrin**

### CODE REVIEW

**Comment by sludtke42** [comment]
Hi Markus,
why is this a pull request for master!?  As I understand, Pawel wants to experiment with the concept and do some timing tests, but at present we don't even have support for this option in the FFTW we distribute. It is very premature to put this into master in any form.

**Comment by ghost** [comment]
I think he just added function call to see how things link. This is in mymodule.c as far as I know and has no impact on anything. 

I’ll look into details in an hour.

**Comment by sludtke42** [comment]
Point is that this sort of thing should be in a branch if it's committed to git at all.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by mstabrin** [comment]
Hello Steve,

I did the change on GitHub directly and somehow it created a pull request immediately.
I just left it there, to make it easily accessible to Pawel and use the automated installation script for pydusa from git.

I will close it now :)

Regarding FFTW:

During rebuilding and reinstalling pydusa we do recompile FFTW with threading option and replace the version.
This has been introduced I guess by Tunay end of 2016 for the first release, so since it did not cause trouble it most likely will not :)

Therefore, we most likely do not need to find an FFTW alternative, as my test seems to have worked.

Best,
Markus



On 26. Sep 2018, at 15:57, Steve Ludtke <notifications@github.com<mailto:notifications@github.com>> wrote:

Point is that this sort of thing should be in a branch if it's committed to git at all.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu<mailto:sludtke@bcm.edu>> Baylor College of Medicine
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology (www.bcm.edu/biochem<http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core (cryoem.bcm.edu<http://cryoem.bcm.edu>)
Co-Director CIBR Center (www.bcm.edu/research/cibr<http://www.bcm.edu/research/cibr>)

**Comment by sludtke42** [comment]
Hmm... interesting point. However, most people who do installations on individual computers do not do a reinstallation of Pydusa, as it is only on clusters where the rebuilding is necessary.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by ghost** [comment]
This is not quite right.  Most functions of SPHIRE will not run at all without MPI.  One has to install it even if there is only one CPU (which I do not think happens anymore).  For a good number of years now I abandoned idea of maintaining MPI and non-MPI versions of the same program, so newer programs require MPI.

**Comment by sludtke42** [comment]
The binaries we distribute include a functioning MPI and Pydusa. The only time they are recompiled is when specialized hardware (such as on clusters) requires a custom OpenMPI build.  This process (installing Pydusa) is something that a large fraction of users is not really able to handle themselves, and on clusters they typically relegate it to support staff. Strangely, doing this on an individual computer is even worse, because, for example, on a Mac, there are no compilers on the machine unless the user is already a developer. (That issue may be handled by the new compiler strategy Anaconda seems to be using, but I'm not really sure). Certainly if we included the full compiler system as a dependency for users just wanting to use the binary distribution it would be a major increase in the size of the package.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by ghost** [comment]
This is correct and in case of Mac rather unfortunate.  The only silver lining is that given the way SPHIRE operates there is not much one can do on a single Mac workstation, that is outside of particle picking, which in turn in case of cryolo requires GPU, so I am not sure whether that would work either.
In short, for all practical purposes current version of SPHIRE can be used only on clusters.

We still have the pending project of new 64 CPUs workstations, but I am not sure whether Dortmund team is still serious about.

**Comment by sludtke42** [comment]
Ok, 
we discussed it internally, and if that flag is missing, I think we have a simple strategy for getting it into the normal binaries in the near future. That is, go ahead and proceed with your testing under the assumption that we will make it work in the binaries somehow in the near future.


--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by sludtke42** [comment]
So, Tunay just checked and said that --enable-threads is included in our FFTW, which we have been compiling ourselves for the binary since we revamped the OpenMPI support long ago.

So, the question has become why you (Pawel) don't see thread support in your installation. As far as we can tell it should be there in all of the source and binary builds following the standard instructions...

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by ghost** [comment]
This is a very good question.  It would of course be infinitely easier to deal with threaded fftw on standard C level rather than further damaging fragile pydusa.

My test was very simple:

I added call:
fftw_init_threads();
to Util.version() in util_sparx.cpp (for no apparent reason, it can be inserted anywhere) and compiled the system on my laptop.  It failed on undefined symbol.

Maybe you could please repeat the test on your installation?  It takes 3 minutes tops and we will know whether it is something I am missing or a deeper problem.

**Comment by sludtke42** [comment]
I just added fftw_init_threads() to one of the methods in emfft.cpp and recompiled on my workstation. No errors. My build environment was done from scratch using the instructions on the Wiki a few months ago.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by ghost** [comment]
That would be very good news as it would save me much grief!  

Was it a Mac or Linux box?

What makes it strange is that I recently refreshed my installation (see below, probably in August, see below.
I will have to look into it as soon as I am done with grant reviewing :-(

Paul-Mac:/Users/pawel 294> ls -lrt EMAN2/eman2
total 304
-rw-rw-r--    1 pawel  staff   2105 Jul 20 10:04 BSD-3-Clause.txt
-rw-rw-r--    1 pawel  staff    884 Jul 20 10:04 README.md
-rwxrwxr-x    1 pawel  staff   8047 Jul 20 10:04 TODO
-rw-rw-r--    1 pawel  staff    936 Jul 20 10:04 appveyor.yml
-rw-rw-r--    1 pawel  staff  18092 Jul 20 10:04 gpl-2.0.txt
drwxrwxr-x   13 pawel  staff    416 Jul 27 11:46 tests
-rw-rw-r--    1 pawel  staff   1069 Aug 15 09:24 CTestTestfile.cmake
-rwxrwxr-x    1 pawel  staff  10771 Aug 28 17:07 CMakeLists.txt
-rw-rw-r--    1 pawel  staff   4769 Aug 28 17:07 Jenkinsfile
drwxrwxr-x   13 pawel  staff    416 Aug 28 17:07 ci_support
drwxrwxr-x   20 pawel  staff    640 Aug 28 17:07 cmake
-rw-rw-r--    1 pawel  staff  28097 Aug 28 17:13 CMakeCache.txt
-rw-rw-r--    1 pawel  staff   2576 Aug 28 17:13 cmake_install.cmake
drwxrwxr-x   21 pawel  staff    672 Sep 18 09:00 broken
-rw-rw-r--    1 pawel  staff  18941 Sep 26 11:21 Makefile
drwxrwxr-x   11 pawel  staff    352 Sep 26 11:21 rt
drwxrwxr-x   15 pawel  staff    480 Sep 26 11:21 pyemtbx

**Comment by sludtke42** [comment]
That was linux.
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Pull request closed without merging**
